export const LIVE_COURSE_LIST_REQUEST = 'LIVE_COURSE_LIST_REQUEST'
export const LIVE_COURSE_LIST_SUCCESS = 'LIVE_COURSE_LIST_SUCCESS'
export const LIVE_COURSE_LIST_FAIL = 'LIVE_COURSE_LIST_FAIL'

export const ONLINE_COURSE_LIST_REQUEST = 'ONLINE_COURSE_LIST_REQUEST'
export const ONLINE_COURSE_LIST_SUCCESS = 'ONLINE_COURSE_LIST_SUCCESS'
export const ONLINE_COURSE_LIST_FAIL = 'ONLINE_COURSE_LIST_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'
