export const COURSE_LIST_REQUEST = 'COURSE_LIST_REQUEST'
export const COURSE_LIST_SUCCESS = 'COURSE_LIST_SUCCESS'
export const COURSE_LIST_FAIL = 'COURSE_LIST_FAIL'
export const COURSE_LIST_RESET = 'COURSE_LIST_RESET'

export const LIVE_COURSE_LIST_REQUEST = 'LIVE_COURSE_LIST_REQUEST'
export const LIVE_COURSE_LIST_SUCCESS = 'LIVE_COURSE_LIST_SUCCESS'
export const LIVE_COURSE_LIST_FAIL = 'LIVE_COURSE_LIST_FAIL'

export const ONLINE_COURSE_LIST_REQUEST = 'ONLINE_COURSE_LIST_REQUEST'
export const ONLINE_COURSE_LIST_SUCCESS = 'ONLINE_COURSE_LIST_SUCCESS'
export const ONLINE_COURSE_LIST_FAIL = 'ONLINE_COURSE_LIST_FAIL'

export const COURSE_DETAILS_REQUEST = 'COURSE_DETAILS_REQUEST'
export const COURSE_DETAILS_SUCCESS = 'COURSE_DETAILS_SUCCESS'
export const COURSE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL'


export const COURSE_CREATE_REVIEW_REQUEST = 'COURSE_CREATE_REVIEW_REQUEST'
export const COURSE_CREATE_REVIEW_SUCCESS = 'COURSE_CREATE_REVIEW_SUCCESS'
export const COURSE_CREATE_REVIEW_FAIL = 'COURSE_CREATE_REVIEW_FAIL'
export const COURSE_CREATE_REVIEW_RESET = 'COURSE_CREATE_REVIEW_RESET'

