export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST'
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS'
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL'

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST'
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS'
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL'

export const JOB_RECRUITER_REGISTER_REQUEST = 'JOB_RECRUITER_REGISTER_REQUEST'
export const JOB_RECRUITER_REGISTER_SUCCESS = 'JOB_RECRUITER_REGISTER_SUCCESS'
export const JOB_RECRUITER_REGISTER_FAIL = 'JOB_RECRUITER_REGISTER_FAIL'
export const JOB_RECRUITER_REGISTER_RESET = 'JOB_RECRUITER_REGISTER_RESET'

export const JOB_APPLICATION_REQUEST = 'JOB_APPLICATION_REQUEST'
export const JOB_APPLICATION_SUCCESS = 'JOB_APPLICATION_SUCCESS'
export const JOB_APPLICATION_FAIL = 'JOB_APPLICATION_FAIL'
export const JOB_APPLICATION_RESET = 'JOB_APPLICATION_RESET'