# Generated by Django 3.1.7 on 2021-07-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20210705_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
