# Generated by Django 3.1.7 on 2021-07-15 06:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='base.Category'),
        ),
        migrations.CreateModel(
            name='CandidateApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('passing_year', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('current_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('work_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('current_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('expected_ctc', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notice_period', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('relocate', models.CharField(blank=True, max_length=200, null=True)),
                ('job_role', models.CharField(blank=True, max_length=200, null=True)),
                ('current_location', models.CharField(blank=True, max_length=200, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.job')),
            ],
        ),
    ]
